export const SET_PRODUCTS = "SET_PRODUCTS";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";

export const GET_PRODUCT = "GET_PRODUCT";
export const CLEAR_PURCHASE_PRODUCT = "CLEAR_PURCHASE_PRODUCT";
export const INCREMENT_PRODUCT_QUANTITY = "INCREMENT_PRODUCT_QUANTITY";
export const DECREMENT_PRODUCT_QUANTITY = "DECREMENT_PRODUCT_QUANTITY";

export const ADD_TO_CART = "ADD_TO_CART";
export const POPULATE_CART = "POPULATE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const USER_AUTH = "USER_AUTH";
